### ISSUE TITLE
Unabled to load maps to connect to a server [0.2.3]

### ISSUE THREAD

**Issue by ObaniGemini** [Siile/Ninslash#37]
`failed to open file. filename='mapres/factory_bg.png'`
`failed to open file. filename='mapres/factory_tiles.png'`

Looking into the files, it seems like they were renamed to `factory_background` and `factory_main`, but maybe not in the "map" source file(s) (happends for lab4 at least)

After changing that, I'm still unabled to join a server, local or not. Are there any verbose options to see what's going on ?
( "I can't connect" => The console shows me as connected but I'm stucked on the loading screen of teeworlds, "Connecting to ...")

**Additional info :**
- OS : Debian 8
- used the Linux binary _and_ a compiled version of current master with bam 5.0
- After staying a long time, I'm "kicked for inactivity", which proves I'm really considered as "on the server"

**Comment by Siile** [comment]
Deleting the map from downloaded maps should help. If it doesn't, delete all traces of the map and join server to redownload it. Sounds like map version conflict.

**Comment by ObaniGemini** [comment]
After deleting all the informations located in .ninslash, nothing changed. Isn't there a "debug" or "verbose" option to launch ninslash ?

**Comment by CytraL** [comment]
The error is in the anti-bot system (that not is the best way for that).... Siile forgot to put m_IsBot to 0.

https://github.com/Siile/Ninslash/blob/master/src/game/client/gameclient.cpp#L1417

adding ```Msg.m_IsBot = 0;``` works ;)

**Comment by ObaniGemini** [comment]
I can confirm this works

**Comment by Siile** [comment]
Thanks for pointing out! Hotfix in 5, 4, 3...
