### ISSUE TITLE
Own server

### ISSUE THREAD

**Issue by SKSaki** [Siile/Ninslash#43]
Is there a way to make own server for this?

**Comment by SKSaki** [comment]
@pelya answer me please?

**Comment by pelya** [comment]
Just launch ninslash_srv and you're done.

Or install Android version and launch the server from the game menu.

**Comment by SKSaki** [comment]
În android server will just appear in lan @pelya 
I want a permanent server...

**Comment by SKSaki** [comment]
What should i do to keep the server running Forever 
I have a vps...
I can keep a server on @pelya

**Comment by Siile** [comment]
Hey @SKSaki, great that you want to host Ninslash!

**Comment by SKSaki** [comment]
Yeah,but how @pelya 
Do You. Have any inatructions? I need some help,cuz its hard for me to host it...
I need installation inatructions....

**Comment by ObaniGemini** [comment]
Learn about how to open a port and then understand how to launch a permanent server

**Comment by pelya** [comment]
VPS should have all ports open already, unless you bought something
extra-cheap, such as lowendspirit VPS.

Are you using Linux on your VPS?

Run command

crontab -e

And add the line

@reboot cd /path/to/ninslash ; ./ninslash_srv -f 'example
configs/autoexec.cfg'

Don't forget to do this:

sudo apt-get install nano

Otherwise you'll get vi as your editor, and you will have to reboot your
VPS using the web admin console to exit vi.

**Comment by SKSaki** [comment]
@pelya i use ovh's vps
But i need help installing ninslash in Linux machine.
Also i have nano.
My Linux version is Ubuntu

**Comment by SKSaki** [comment]
Also,i use pm2 for automating tasks
Idk how to use cron,or the path to ninslash :(
@pelya

**Comment by SKSaki** [comment]
Also,that leads me to an error...

**Comment by SKSaki** [comment]
GNU nano 2.5.3    File: /tmp/crontab.0PZulI/crontab              
# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
#
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),           # and day of week (dow) or use '*' in these fields (for 'any').#
# Notice that tasks will be started based on the cron's system
  GNU nano 2.5.3    File: /tmp/crontab.0PZulI/crontab    Modified  
# daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected$#
# For example, you can run a backup of all your user accounts
  GNU nano 2.5.3    File: /tmp/crontab.xN2V3I/crontab              
# daemon's notion of time and timezones.
#                                                                  # Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected$#
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
#
# For more information see the manual pages of crontab(5) and cron$#                                                                  # m h  dom mon dow   command                                       


  GNU nano 2.5.3    File: /tmp/crontab.xN2V3I/crontab    Modified  
# daemon's notion of time and timezones.                           #
# Output of the crontab jobs (including errors) is sent through    # email to the user the crontab file belongs to (unless redirected$ ; ./ninslash_srv -f 'example                                        GNU nano 2.5.3    File: /tmp/crontab.xN2V3I/crontab              
# daemon's notion of time and timezones.
#
  GNU nano 2.5.3    File: /tmp/crontab.xN2V3I/crontab              # daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected$#
# For example, you can run a backup of all your user accounts      # at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
#
# For more information see the manual pages of crontab(5) and cron$#
# m h  dom mon dow   command
cd /Ninslash ; ./ninslash_srv -f 'example
configs/autoexec.cfg'                                              



crontab: installing new crontab
"/tmp/crontab.xN2V3I/crontab":22: bad minute
errors in crontab file, can't install.
Do you want to retry the same edit? (y/n) n
crontab: edits left in /tmp/crontab.xN2V3I/crontab
saki@SakiVPS:~$ @pelya

**Comment by pelya** [comment]
You can download Ninslash Linux build right from ninslash.com, it has all
necessary files to run dedicated server.

You'll need to update it each time when there's a new release, I had a
script to do that for you - pull latest changes directly from Git once per
day and compile it, I'll copy it here when I'll get to my PC.

Run command

mkdir ninslash

cd ninslash

wget http://ninslash.com/ninslash_unix.zip

unzip ninslash_unix.zip

chmod a+x ninslash_srv

Then do that 'crontab -e' thing I've described above:

crontab -e

Add this line

@reboot cd /home/$USER/ninslash ; ./ninslash_srv -f 'example
configs/autoexec.cfg' >server.log 2>&1

Also you may add a command to reboot your VPS once per day, because the
server sometimes freezes:

sudo crontab -e

Add this line:

0 4 * * * /sbin/shutdown -r +5

Reboot your VPS, ninslash server should be running.


On Jun 25, 2017 1:03 AM, "SKSaki" <notifications@github.com> wrote:

@pelya <https://github.com/pelya> i use ovh's vps
But i need help installing ninslash in Linux machine.
Also i have nano.
My Linux version is Ubuntu

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Siile/Ninslash/issues/43#issuecomment-310868541>, or mute
the thread

**Comment by pelya** [comment]
You forgot @reboot at the beginning of the crontab line.

**Comment by SKSaki** [comment]
The same error

**Comment by SKSaki** [comment]
@reboot cd /home/$USER/ninslash ; ./ninslash_srv -f
'example                                                           configs/autoexec.cfg' >server.log 2>&1




crontab: installing new crontab
"/tmp/crontab.9zSyef/crontab":23: bad minute
errors in crontab file, can't install.
Do you want to retry the same edit? (y/n)
@pelya 
#idk what is wrong...

**Comment by SKSaki** [comment]
**what that means**

**Comment by SKSaki** [comment]
I did that.
Whats next @pelya

**Comment by pelya** [comment]
Please put it as a single line, do not split the command into two lines

**Comment by SKSaki** [comment]
Yeah @pelya, i figured it.
I succesfuly made the crontab,but what now,my server is still bot on even after restart

**Comment by SKSaki** [comment]
So what now @pelya

**Comment by SKSaki** [comment]
Hey @pelya
I figured out an issue...
My server cant let clients Connect to IT.  
Because the port is not opened.
Here is what log say
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-81-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Mon Jun 26 05:11:12 2017 from 93.122.250.69
saki@SakiVPS:~$ crontab -l
# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
#
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').#
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
[59507c57][server]: added option '-                   ' 'sv_null 0'[59507c57][server]: added option 'Gamemode: Invasion (co-op)' 'sv_$[59507c57][server]: added option 'Gamemode: Reactor defence (co-op$[59507c57][server]: added option 'Gamemode: Team Death Match' 'sv_$[59507c57][server]: added option 'Gamemode: Capture The Flag' 'sv_$[59507c57][server]: added option 'Gamemode: Death Match' 'sv_gamet$[59507c57][server]: added option 'Gamemode: Chainsaw Infection' 's$[59507c57][server]: added option 'Gamemode: Gun Game' 'sv_gametype$[59507c57][server]: added option '-' 'sv_null 0'
[59507c57][server]: added option 'Reload' 'reload'                 [59507c57][server]: added option '- ' 'sv_null 0'                  [59507c57][server]: added option 'Next map' 'change_map'           [59507c57][server]: added option '-  ' 'sv_null 0'                 [59507c57][server]: added option 'Random start weapon ON' 'sv_rand$[59507c57][server]: added option 'Random start weapon OFF' 'sv_ran$[59507c57][server]: added option '-   ' 'sv_null 0'                [59507c57][server]: added option 'Survival mode ON' 'sv_survivalmo$  GNU nano 2.5.3         File: server.log                Modified  
[59507c57][engine/mastersrv]: refreshing master server addresses   [59507c57][register]: refreshing ip addresses                      [59507c57][engine/mastersrv]: saving addresses
[59507c57][register]: fetching server counts                       [59507c5a][register]: chose 'vps301894.ovh.net' as master, sending$[59507c8e][register]: ERROR: the master server reports that client$[59507c8e][register]: ERROR: configure your firewall/nat to let th$[59507c9d][register]: ERROR: the master server reports that client$[59507c9d][register]: ERROR: configure your firewall/nat to let th$[59507cac][register]: ERROR: the master server reports that client$[59507cac][register]: ERROR: configure your firewall/nat to let th$[59507cbb][register]: ERROR: the master server reports that client$$let through udp on port 8303.


  GNU nano 2.5.3         File: server.log                Modified  
[59507c57][engine/mastersrv]: refreshing master server addresses
[59507c57][register]: refreshing ip addresses                      [59507c57][engine/mastersrv]: saving addresses
[59507c57][register]: fetching server counts
[59507c5a][register]: chose 'vps301894.ovh.net' as master, sending$[59507c8e][register]: ERROR: the master server reports that client$[59507c8e][register]: ERROR: configure your firewall/nat to let th$[59507c9d][register]: ERROR: the master server reports that client$[59507c9d][register]: ERROR: configure your firewall/nat to let th$[59507cac][register]: ERROR: the master server reports that client$[59507cac][register]: ERROR: configure your firewall/nat to let th$[59507cbb][register]: ERROR: the master server reports that client$$let through udp on port 8303.

**Comment by SKSaki** [comment]
@Siile a bit of help?

**Comment by SKSaki** [comment]
Well,i managed to do it myself
Thx anyways
