### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by SKSaki** [Siile/Ninslash#46]
Ok,i saw the server has commands
But what commands are they,what they do.
Are You kind to list me all server commands?
(Those You access with !password)
I cant see them on android.
@pelya @siile

**Comment by pelya** [comment]
Same as in TeeWorlds.

https://www.teeworlds.com/?page=docs&wiki=server_commands

**Comment by Siile** [comment]
Hey, here's part 1:
https://github.com/Siile/Ninslash/blob/master/src/engine/shared/config_variables.h#L102

Part 2:
https://github.com/Siile/Ninslash/blob/master/src/game/variables.h#L66

**Comment by SKSaki** [comment]
Thanks guys
